---
title: "Chiu et al. 2025"
subtitle: "Photoaffinity Labeling Reveals a Role for the Unusual Triply Acylated Phospholipid N-Acylphosphatidylethanolamine in Lactate Homeostasis"
date: 2025-03-06
format: 
  html:
    embed-resources: false
standalone: false
---

::: {.callout-note collapse="true"}

{{< include /StudyInformation_includes/DCC_2025_include.qmd >}}

:::


## Data visualization
 

```{r setup_and_data_wrangling, echo=FALSE, warning=FALSE, include=FALSE}
library(here)

## Opening the source file for the ggplot custom theme
source(paste0(here::here(), "/Resources/ggplot_styles.R"))

data <- readr::read_csv(paste0(here::here(), "/IndividualStudies/DataTables/DCC_2025_ChemrXiv_FullDataset.csv")) |> 
  group_by(gene_name) |>
  filter(ratio_MvsL != "") |>
  summarise(logFC = mean(log2(ratio_MvsL)),
            pvalue = mean(pvalue),
            numReplicates = n(),
            AveExpr = log10(mean(L_abundance) + mean(M_abundance))/2) |>
  arrange(-logFC) |>
  mutate(LipidProbe = "BF-NAPE",
         hit_annotation = case_when(.default = "no hit",
                                    logFC >= 0.5849625 & pvalue <= 0.01 & numReplicates == 2 ~ "enriched candidate",
                                    logFC >= 0.5849625 & pvalue <= 0.01 & numReplicates == 3 ~ "enriched hit")) |>
  glimpse()

median_logFC <- median(data$logFC)

data$logFC <- data$logFC - median_logFC

# Organize the hit annotations as factors
data$hit_annotation <- factor(pull(data, hit_annotation), levels = c("enriched hit", "hit", "enriched candidate", "candidate", "no hit", "NA"), ordered = TRUE)

```

::::{.border}
::: {.panel-tabset}

#### Volcano plots

```{r, echo=FALSE, warning=FALSE}
#| fig-cap: "Volcano plots depict the relative enrichment of each protein versus non-crosslinked control (x-axis) and the statistical significance of each protein following a Student's t-test (y-axis, -log10 transformed). Black proteins are identified in only one replicate, Purple enriched candidates are defined as proteins identified in two replicates & fold-change > 1.5 (logFC 0.585) & pvalue < 0.01, and Orange enriched hits are defined as proteins identified in all three replicates & fold-change > 1.5 (logFC 0.585) & pvalue < 0.01)."

VolcanoPlotStandardized(data)

```


#### Ranked-order plots

```{r, echo=FALSE, warning=FALSE}
#| fig-cap: "Ranked-order plots depict the relative enrichment of each protein versus non-crosslinked control (y-axis) from lowest to highest. Black proteins are identified in only one replicate, Purple enriched candidates are defined as proteins identified in two replicates & fold-change > 1.5 (logFC 0.585) & pvalue < 0.01, and Orange enriched hits are defined as proteins identified in all three replicates & fold-change > 1.5 (logFC 0.585) & pvalue < 0.01)."

RankedOrderPlotStandard(data)
```


#### MA Plots

```{r, echo=FALSE, warning=FALSE}
#| fig-cap: "MA plots depict the average abundance of each protein in the crosslinked and uncrosslinked conditions (x-axis) versus the log2-transformed fold-change between the crosslinked and uncrosslinked conditions (y-axis). Black proteins are identified in only one replicate, Purple enriched candidates are defined as proteins identified in two replicates & fold-change > 1.5 (logFC 0.585) & pvalue < 0.01, and Orange enriched hits are defined as proteins identified in all three replicates & fold-change > 1.5 (logFC 0.585) & pvalue < 0.01)."

MAStandard(data)

```


#### Venn Diagram

```{r Venn_wrangling, include=FALSE, warning=FALSE}

###### Wrangling for the Venn Diagram ######
# Read the dataset
VennData <- readr::read_csv(paste0(here::here(), "/LipidProbe/DataSets/DCC_2025_ChemrXiv_FilteredDataset.csv"))

# Separates out each of the genesets, then forces them back together in a vectorized list.
A_proteins <- VennData |>
  filter(Replicate == "A") |>
  dplyr::select(gene_name)

B_proteins <- VennData |>
  filter(Replicate == "B") |>
  dplyr::select(gene_name)

C_proteins <- VennData |>
  filter(Replicate == "C") |>
  dplyr::select(gene_name)

VennList <- list("Replicate A" = as.list(A_proteins$gene_name), "Replicate B" = as.list(B_proteins$gene_name), "Replicate C" = as.list(C_proteins$gene_name))
```

```{r NAPE_Venn, echo=FALSE, warning=FALSE}
#| fig-cap: "A Venn diagram depicts the overlapping identification of proteins between the three replicates. The full dataset was filtered to only include proteins with fold-change > 1.5 (logFC > 0.585) and p-value < 0.01 There are 88 proteins enriched uniquely in Replicate A, 75 proteins enriched uniquely in Replicate B, and 64 proteins enriched uniquely in Replicate C."

ggvenn <- ggvenn(VennList,
                      show_percentage = FALSE,
                      show_elements = FALSE,
                      fill_color = c("orange", "purple", "blue")) +
        labs(x = "", y = "") +
        theme_minimal()

ggvenn

```

:::
::::

## Data exploration

:::{.border}
```{r NAPE_DataTable, echo=FALSE, warning=FALSE}

# Here is the code to make the filterable lists shown in the crosstalk table below

data <- data |>
  dplyr::select(gene_name, LipidProbe, hit_annotation, logFC, pvalue, numReplicates) |>
  mutate(logFC = signif(logFC, digits=3),
          pvalue = signif(pvalue, digits=3)) |>
  arrange(hit_annotation, numReplicates, -logFC)

## Creates a reactive dataframe
data_reactive <- crosstalk::SharedData$new(data)

htmltools::tags$div(
  class = "filter-container",
  filter_checkbox(id = "LipidProbe",
                  label = "Lipid probe in pulldown:", 
                  sharedData = data_reactive,
                  group = ~LipidProbe),
  filter_checkbox(id = "hit_annotation",
                  label = "Enrichment criteria:", 
                  sharedData = data_reactive,
                  group = ~hit_annotation)
)

## Displays the reactive dataframe
datatable(data_reactive, 
          caption = "This datatable contains all the data plotted above. Check the boxes below to filter the dataset by which lipid probe was used in the pulldown and by significance thresholds. logFC ratios are median normalized. \"Num Replicate IDs\" denotes the number of replicates in which the protein was identified. As above, \"enriched hit\" denotes proteins identified in all three replicates & fold-change > 1.5 (logFC 0.585) & pvalue < 0.01. \"enriched candidates\" are proteins identified in two replicates & fold-change > 1.5 (logFC 0.585) & pvalue < 0.01.",
          options = list(pageLength = 10),
                         colnames = c("Gene Name", "Lipid Probe", "Hit Annotation", "LogFC", "p value", "Num Replicate IDs"),
                         rownames=FALSE)

```



:::

<br>

```{r save_csv, include=FALSE, echo=FALSE, warning=FALSE}

# write_csv(data, paste0(here(), "/LipidProbe/DataSets/DCC_2025_ChemrXiv_Download.csv"))

```

## Data download

{{< downloadthis DataTables/DCC_2025_ChemrXiv_Download.csv dname="DCC_2025_ChemrXiv_Download">}}
