---
title: "Muller et al. 2021"
subtitle: "Synthesis and Cellular Labeling of Multifunctional Phosphatidylinositol *Bis*- and *Tris*phosphate Derivatives"
date: 2021-06-01
format: 
  html:
    embed-resources: false
standalone: false
---

```{r setup, echo=FALSE, include=FALSE}
## intitialize libraries
library(here)

## Opening the source file for the ggplot custom theme
source(paste0(here(), "/Resources/ggplot_styles.R"))


# Opening the datatable for this page
RM_2021_data <- readr::read_csv(here("IndividualStudies/DataTables/RM_Angewandte_2021_download.csv")) |>
  mutate(
    hit_annotation = case_when(
      hit_annotation == "enriched hit" & logFC < 0 ~ "hit",
      hit_annotation == "enriched candidate" & logFC < 0 ~ "candidate",
      .default = hit_annotation
    )
  )

# Organize the hit annotations as factors
RM_2021_data$hit_annotation <- factor(pull(RM_2021_data, hit_annotation), levels = c("enriched hit", "hit", "enriched candidate", "candidate", "no hit",  "NA"), ordered=TRUE)  

RM_2021_data <- RM_2021_data |>
  arrange(hit_annotation) |>
  glimpse()
```

::: {.callout-note collapse="true"}

{{< include /StudyInformation_includes/RM_2021_include.qmd >}}

:::

::: {.callout-tip}

## Membrane Fraction

```{r FilteringForMembraneProteins, include=FALSE, echo=FALSE}
data <- RM_2021_data |>
  filter(Fraction == "Membrane (+UV vs -UV)")

```

### Data visualization


::: {.panel-tabset}

#### Volcano plots

:::{.border}
```{r, echo=FALSE, warning=FALSE}
#| fig-cap: "Volcano plots depict the relative enrichment of each protein versus non-crosslinked control (x-axis) and the statistical significance of each protein following a Student's t-test (y-axis, -log10 transformed). The left panel depicts the results of a pulldown using trifunctionalized phosphatidic acid; the right panel depicts the results of the pulldown using trifunctionalized phosphatidylethanolamine. Black proteins are unenriched or depleted in the presence of probe, Purple enriched candidates are defined as proteins with a false discovery rate less than 0.2 and a fold change of at least 1.5-fold, and Orange enriched hits are defined as proteins with a false discovery rate less than 0.05 and a fold change of at least 2-fold in the +UV over the -UV)."

VolcanoPlotStandardized(data)

```
:::


#### Ranked-order plots

:::{.border}
```{r, echo=FALSE, warning=FALSE}
#| fig-cap: "Ranked-order plots depict the relative enrichment of each protein versus non-crosslinked control (y-axis) from lowest to highest. The left panel depicts the results of a pulldown using trifunctionalized phosphatidic acid; the right panel depicts the results of the pulldown using trifunctionalized phosphatidylethanolamine. Black proteins are unenriched or depleted in the presence of probe, Purple enriched candidates are defined as proteins with a false discovery rate less than 0.2 and a fold change of at least 1.5-fold, and Orange enriched hits are defined as proteins with a false discovery rate less than 0.05 and a fold change of at least 2-fold in the +UV over the -UV)."

RankedOrderPlotStandard(data)
```
:::


#### MA Plots

:::{.border}
```{r, echo=FALSE, warning=FALSE}
#| fig-cap: "MA plots depict the average abundance of each protein in the crosslinked and uncrosslinked conditions (x-axis) versus the log2-transformed fold-change between the crosslinked and uncrosslinked conditions (y-axis). Black proteins are unenriched or depleted in the presence of probe, Purple enriched candidates are defined as proteins with a false discovery rate less than 0.2 and a fold change of at least 1.5-fold, and Orange enriched hits are defined as proteins with a false discovery rate less than 0.05 and a fold change of at least 2-fold in the +UV over the -UV)."

MAStandard(data)

```

:::
:::
:::

::: {.callout-tip}

## Cytosolic Fraction

```{r FilteringForCytosolProteins, include=FALSE, echo=FALSE}
data <- RM_2021_data |>
  filter(Fraction == "Cytosol (+UV vs -UV)")

```

### Data visualization


::: {.panel-tabset}

#### Volcano plots

:::{.border}
```{r, echo=FALSE, warning=FALSE}
#| fig-cap: "Volcano plots depict the relative enrichment of each protein versus non-crosslinked control (x-axis) and the statistical significance of each protein following a Student's t-test (y-axis, -log10 transformed). The left panel depicts the results of a pulldown using trifunctionalized phosphatidic acid; the right panel depicts the results of the pulldown using trifunctionalized phosphatidylethanolamine. Black proteins are unenriched or depleted in the presence of probe, Purple enriched candidates are defined as proteins with a false discovery rate less than 0.2 and a fold change of at least 1.5-fold, and Orange enriched hits are defined as proteins with a false discovery rate less than 0.05 and a fold change of at least 2-fold in the +UV over the -UV)."

VolcanoPlotStandardized(data)

```
:::


#### Ranked-order plots

:::{.border}
```{r, echo=FALSE, warning=FALSE}
#| fig-cap: "Ranked-order plots depict the relative enrichment of each protein versus non-crosslinked control (y-axis) from lowest to highest. The left panel depicts the results of a pulldown using trifunctionalized phosphatidic acid; the right panel depicts the results of the pulldown using trifunctionalized phosphatidylethanolamine. Black proteins are unenriched or depleted in the presence of probe, Purple enriched candidates are defined as proteins with a false discovery rate less than 0.2 and a fold change of at least 1.5-fold, and Orange enriched hits are defined as proteins with a false discovery rate less than 0.05 and a fold change of at least 2-fold in the +UV over the -UV)."

RankedOrderPlotStandard(data)
```
:::


#### MA Plots

:::{.border}
```{r, echo=FALSE, warning=FALSE}
#| fig-cap: "MA plots depict the average abundance of each protein in the crosslinked and uncrosslinked conditions (x-axis) versus the log2-transformed fold-change between the crosslinked and uncrosslinked conditions (y-axis). Black proteins are unenriched or depleted in the presence of probe, Purple enriched candidates are defined as proteins with a false discovery rate less than 0.2 and a fold change of at least 1.5-fold, and Orange enriched hits are defined as proteins with a false discovery rate less than 0.05 and a fold change of at least 2-fold in the +UV over the -UV)."

MAStandard(data)

```

:::
:::
:::

## Data exploration

Check the boxes below to filter the dataset by which lipid probe was used in the pulldown and by significance thresholds.


:::{.border}
```{r, echo=FALSE}

RM_2021_data <- RM_2021_data |>
  select(-hit_annotation_method) |>
  mutate(
    logFC = signif(logFC, digits = 4),
    pvalue = signif(pvalue, digits = 4),
    AveExpr = signif(AveExpr, digits = 4),
    fdr = signif(fdr, digits = 4)
  )

# Here is the code to make the filterable lists shown in the crosstalk table below

## Creates a reactive dataframe
data_reactive <- crosstalk::SharedData$new(RM_2021_data)


htmltools::tags$div(
  class = "filter-container",
  filter_checkbox(id = "LipidProbe",
                  label = "Lipid probe in pulldown:", 
                  sharedData = data_reactive,
                  group = ~LipidProbe),
  filter_checkbox(id = "hit_annotation",
                  label = "Enrichment criteria:", 
                  sharedData = data_reactive,
                  group = ~hit_annotation),
  filter_checkbox(id = "Fraction",
                  label = "Cellular fraction",
                  sharedData = data_reactive,
                  group = ~Fraction)
)

## Displays the reactive dataframe
datatable(data_reactive, options = list(pageLength = 10))

```

NB: Data analysis overview pending.
:::


## Data download

{{< downloadthis DataTables/RM_Angewandte_2021_download.csv dname="RM_Angewandte_2021">}}


