---
title: "The Lipid Interactome Repository"
format: 
  html:
    embed-resources: false
standalone: false
---

## Site Overview

<!-- **This repository is still under construction, please forgive us for incomplete sections as we build features!** -->

The goal of this site is to increase the accessibility of proteomics data utilizing multi-functionalized lipid analogs/probes to identify the lipid:protein interactions of biologically active lipids. 

Explore the lipids below to see their published interactomes.


## Need more info?

See our [Functional Lipid Probes Overview](/Background/MultifunctionalLipidProbesOverview.qmd) for more details about how these lipid analogs are used. 

See our [Proteomics Methodology Overview](/Background/ProteomicsUsingMultifunctionalProbes.qmd) for more details about the quantification methods used in the data presented in this repository.

See our [Data Analysis Overview](/Background/DataAnalysisAndStatistics.qmd) for more details about the data analysis between the raw mass spectrometry data and the final data presented here.

## Lipid Interactomes

```{=html}
<div style="text-align: center; margin: 20px;">
  <a href="LipidProbe/PhosphatidicAcid.qmd" style="text-decoration: none;">
      <button style="background-color: #97bdef; color: white; font-size: 20px; padding: 15px 30px; border: none; border-radius: 8px; margin: 10px; cursor: pointer;">
          Phosphatidic Acid
      </button>
  </a>
  <a href="LipidProbe/Phosphatidylethanolamine.qmd" style="text-decoration: none;">
      <button style="background-color: #2986cc; color: white; font-size: 20px; padding: 15px 30px; border: none; border-radius: 8px; margin: 10px; cursor: pointer;">
          Phosphatidylethanolamine
      </button>
  </a>

   <a href="LipidProbe/N-Acylphosphatidylethanolamine.qmd" style="text-decoration: none;">
      <button style="background-color:rgb(41, 188, 204); color: white; font-size: 20px; padding: 15px 30px; border: none; border-radius: 8px; margin: 10px; cursor: pointer;">
          N-Acylphosphatidylethanolamine (NAPE)
      </button>
  </a>

    <br>

    <a href="LipidProbe/Phosphatidylinositol.qmd" style="text-decoration: none;">
        <button style="background-color: rgb(231, 109, 104); color: white; font-size: 20px; padding: 15px 30px; border: none; border-radius: 8px; margin: 10px; cursor: pointer;">
            Phosphatidylinositol (PI)
        </button>
    </a>

    <br>

    <a href="LipidProbe/PhosphatidylinositolBisphosphate.qmd" style="text-decoration: none;">
        <button style="background-color: #f14334; color: white; font-size: 20px; padding: 15px 30px; border: none; border-radius: 8px; margin: 10px; cursor: pointer;">
            PI(4,5)P<sub>2</sub>
        </button>
    </a>

    <a href="LipidProbe/PhosphatidylinositolTrisphosphate.qmd" style="text-decoration: none;">
        <button style="background-color:rgb(223, 21, 21); color: white; font-size: 20px; padding: 15px 30px; border: none; border-radius: 8px; margin: 10px; cursor: pointer;">
            PI(3,4,5)P<sub>3</sub>
        </button>
    </a>

    <br>
    <a href="LipidProbe/Diacylglycerol.qmd" style="text-decoration: none;">
        <button style="background-color: #2ecc71; color: white; font-size: 20px; padding: 15px 30px; border: none; border-radius: 8px; margin: 10px; cursor: pointer;">
            Diacylglycerol
        </button>
    </a>

    <br>
    <a href="LipidProbe/Sphinganine.qmd" style="text-decoration: none;">
        <button style="background-color:rgb(101, 46, 204); color: white; font-size: 20px; padding: 15px 30px; border: none; border-radius: 8px; margin: 10px; cursor: pointer;">
            Sphinganine
        </button>
    </a>
    <a href="LipidProbe/Sphingosine.qmd" style="text-decoration: none;">
        <button style="background-color:rgb(202, 52, 235); color: white; font-size: 20px; padding: 15px 30px; border: none; border-radius: 8px; margin: 10px; cursor: pointer;">
            Sphingosine
        </button>
    </a>

    <br>
	<a href="LipidProbe/8-3_FattyAcid.qmd" style="text-decoration: none;">
        <button style="background-color:rgb(235, 177, 52); color: white; font-size: 20px; padding: 15px 30px; border: none; border-radius: 8px; margin: 10px; cursor: pointer;">
            8-3 Fatty Acid
        </button>
    </a>

    <a href="LipidProbe/1-10_FattyAcid.qmd" style="text-decoration: none;">
        <button style="background-color:rgb(237, 111, 38); color: white; font-size: 20px; padding: 15px 30px; border: none; border-radius: 8px; margin: 10px; cursor: pointer;">
            1-10 Fatty Acid
        </button>
    </a>
</div>
```