---

format: 
  docx:
    reference-doc: custom-reference-doc.docx
  # pdf: 
  #   latex-engine: pdflatex
---

Dear Dr. Hutchins,

We thank you again for the opportunity to address the reviewers' comments on our first draft of our manuscript -- we have included with this letter an updated mansucript draft and have incorporated as many of their suggestions as we could feasibly achieve in the Lipid Interactome site. 

We are grateful for thought that the reviewers put into their comments. We interpreted several throughlines in their comments: 1. Requests for additional metadata about study methodology and the incorporation of additional data (e.g. accession numbers in addition to gene names), 2. Requests for additional information about data submission, processing, and harmonization methods, 3. Requests for an automated/scalable data submission pipeline, and 4. The identification of typographical errors, malformed links, and bugs in the site.

Many of these points have been addressed directly either in the text or on the Lipid Interactome repository. For example, the broken links and typographical errors in figure captions have been addressed, additional cell line information has been added to our *Comparing the Enriched Hits of Different Probes* Shiny app, we have included of accession number to convey crucial information about isoform identifications in addition to using gene name to identify hits (where possible in the original datasets; the authors of Hoglinger 2017 have been unresponsive and we do not have the accession number data for their results) and clarification about the qualitative nature of the comparisons displayed in the Shiny app. We have additionally provided links to download the R scripts were used to "wrangle" the submitted data to the formats that our data visualization functions accept. 

We highly concur with the reviewers' request for an automated data submission system. At present, this site has been built, managed, and maintained through the efforts of a single individual and we do not currently have the resources to overhaul the site to sufficiently incorporate these needs; we are seeking additional funding from the Open Oregon Educational Resources and the Code for Science and Society programs to support this individual in building these functionalities into our site. It is a long-term vision of our group to build a more scalable version of this repository which requires minimal manual management and enables automated data submission. However, we further feel that the underlying architecture of this repository is independent of its utility to the external lipid research community. 

