#### Study details

##### Authors
Sayan Kundu, Mohit Jaiswal, Venkanna Babu Mullapudi, Jiatong Guo, Manasi Kamat, Kari B. Basso, Zhongwu Guo


##### Journal
Chemistry - A European Journal
<https://doi.org/10.1002/chem.202303047>{target="_blank"}

##### Abstract

Glycosylphosphatidylinositols (GPIs) need to interact with other components in the cell membrane to transduce transmembrane signals. A bifunctional GPI probe was employed for photoaffinity‐based proximity labelling and identification of GPI‐interacting proteins in the cell membrane. This probe contained the entire core structure of GPIs and was functionalized with photoreactive diazirine and clickable alkyne to facilitate its crosslinking with proteins and attachment of an affinity tag. It was disclosed that this probe was more selective than our previously reported probe containing only a part structure of the GPI core for cell membrane incorporation and an improved probe for studying GPI‐cell membrane interaction. Eighty‐eight unique membrane proteins, many of which are related to GPIs/GPI‐anchored proteins, were identified utilizing this probe. The proteomics dataset is a valuable resource for further analyses and data mining to find new GPI‐related proteins and signalling pathways. A comparison of these results with those of our previous probe provided direct evidence for the profound impact of GPI glycan structure on its interaction with the cell membrane.

##### Lipid probes utilized

Bifunctional Glycosylphosphatidylinositol (bf-GPI)

Bifunctional phosphatidyl moiety with \alpha&-D-glucoside (Control)

##### Cell line analyzed

[HeLa](https://www.atcc.org/products/ccl-2){target="_blank"} 

#### Uncaging & Crosslinking timeline

| Lipid Probe | Uptake time | Uncaging time | Interaction time | Crosslinking time |
|:-------|:------:|:------:|:------:|:------:|
| bf-GPI |  180 min | NA  | NA | 15 min  |
| Control |  180 min | NA  | NA | 15 min  |


##### Mass spectrometry quantification method

Precursor ion intensity Label Free Quantitation (LFQ), performed using Proteome Discoverer

##### Additional sample preparation <span class="help-symbol" title="e.g. sub-cellular fractionation, depletion, etc.">?</span>

#### Data wrangling
Use the download button below to download the R script used to wrangle the authors' original submission into the data visualization tools on the Lipid Interactome:

{{< downloadthis /Users/gaelenguzman/LipidInteractomics_Website_local/LipidInteractomics_Website/IndividualStudies/DataTables/DataWrangling/SK_2024_wrangling.R dname="SK_2024_wrangling">}}


Use the download button below to download the original data file prior to wrangling: 

{{< downloadthis /Users/gaelenguzman/LipidInteractomics_Website_local/LipidInteractomics_Website/IndividualStudies/DataTables/DataWrangling/SK_2024_fullDataset_originalHandoff.csv dname="SK_2024_ChemEuro_OriginalData">}}



